var bridgesArray = [
{name:"WHITESTONE EXP NB", numerical_rating:4.656,verbal_rating:"FAIR"},
{name:"BRUCKNER EXPWY SVC RD",numerical_rating:3.565,verbal_rating:"FAIR"},
{name:"NEREID AVE (E 240TH ST)",numerical_rating:4.500,verbal_rating:"FAIR"},
{name:"MACOMBS DAM BRIDGE",numerical_rating:3.930,verbal_rating:"FAIR"},
{name:"91 PLACE (2247010)",numerical_rating:6.500,verbal_rating:"VGOOD"},
{name:"67 AVE PED BR (2247200)",numerical_rating:4.219,verbal_rating:"FAIR"},
{name:"51 AVE PED BR (2247280)",numerical_rating:3.018,verbal_rating:"FAIR"},
{name:"METROPOLITAN AVE",numerical_rating:3.603,verbal_rating:"FAIR"},
{name:"NORTHERN BLVD WB",numerical_rating:4.338,verbal_rating:"FAIR"},
{name:"NORTHERN BLVD EB",numerical_rating:4.268,verbal_rating:"FAIR"},
{name:"N.BLVD WB TO 678I SB",numerical_rating:5.619,verbal_rating:"GOOD"},
{name:"BRONX RIVER PKWY",numerical_rating:5.138,verbal_rating:"GOOD"},
{name:"HAMILTON PLACE",numerical_rating:5.528,verbal_rating:"GOOD"},
{name:"GRAND AVE",numerical_rating:4.861,verbal_rating:"FAIR"},
{name:"69TH STREET",numerical_rating:5.056,verbal_rating:"GOOD"},
{name:"495I  (2066000)",numerical_rating:5.479,verbal_rating:"GOOD"},
{name:"5TH AVE",numerical_rating:5.063,verbal_rating:"GOOD"},
{name:"BRUCKNER EXPWY SB",numerical_rating:4.972,verbal_rating:"FAIR"},
{name:"BRUCKNER EXPWY NB",numerical_rating:4.418,verbal_rating:"FAIR"},
{name:"E 174TH ST",numerical_rating:3.986,verbal_rating:"FAIR"},
{name:"174TH ST-NTH PED BRDG",numerical_rating:4.833,verbal_rating:"FAIR"},
{name:"174TH ST-STH PED BRDG",numerical_rating:4.750,verbal_rating:"FAIR"},
{name:"WASHINGTON BRIDGE",numerical_rating:4.493,verbal_rating:"FAIR"},
{name:"BRUCKNER EXPWY SB",numerical_rating:5.698,verbal_rating:"GOOD"},
{name:"BRUCKNER EXPWY NB",numerical_rating:6.190,verbal_rating:"VGOOD"},
{name:"E TREMONT AVE",numerical_rating:4.528,verbal_rating:"FAIR"},
{name:"WESTCHESTER AVE",numerical_rating:4.097,verbal_rating:"FAIR"},
{name:"BRONX PELHAM PKWY",numerical_rating:3.974,verbal_rating:"FAIR"},
{name:"HUTCHINSON RVR PKWY",numerical_rating:4.578,verbal_rating:"FAIR"},
{name:"BE NB SERVICE RD",numerical_rating:4.895,verbal_rating:"FAIR"},
{name:"BE SB SERVICE RD",numerical_rating:5.079,verbal_rating:"GOOD"},
{name:"DEPOT PLACE",numerical_rating:4.319,verbal_rating:"FAIR"},
{name:"BRUCKNER EXPWY",numerical_rating:4.433,verbal_rating:"FAIR"},
{name:"HHP VIADUCT",numerical_rating:3.597,verbal_rating:"FAIR"},
{name:"PED BR AT W 73RD ST",numerical_rating:3.812,verbal_rating:"FAIR"},
{name:"W72ND ST RAMP TO HHP NB",numerical_rating:6.648,verbal_rating:"VGOOD"},
{name:"W 79 ST",numerical_rating:4.424,verbal_rating:"FAIR"},
{name:"HHP",numerical_rating:5.267,verbal_rating:"GOOD"},
{name:"HHP SB",numerical_rating:4.455,verbal_rating:"FAIR"},
{name:"HHP NB",numerical_rating:4.182,verbal_rating:"FAIR"},
{name:"HHP SB",numerical_rating:5.133,verbal_rating:"GOOD"},
{name:"HHP NB",numerical_rating:5.300,verbal_rating:"GOOD"},
{name:"HHP",numerical_rating:4.155,verbal_rating:"FAIR"},
{name:"RAMP TO N.B. HHP",numerical_rating:3.736,verbal_rating:"FAIR"},
{name:"W 181ST ST PED BRDG",numerical_rating:4.418,verbal_rating:"FAIR"},
{name:"HHP",numerical_rating:5.069,verbal_rating:"GOOD"},
{name:"W 232ND ST",numerical_rating:5.026,verbal_rating:"GOOD"},
{name:"W 236TH ST PED BRDG",numerical_rating:3.780,verbal_rating:"FAIR"},
{name:"W 239TH ST",numerical_rating:5.053,verbal_rating:"GOOD"},
{name:"MANHATTAN COLL PKWY",numerical_rating:5.053,verbal_rating:"GOOD"},
{name:"W 246TH ST",numerical_rating:4.868,verbal_rating:"FAIR"},
{name:"W 252ND ST",numerical_rating:5.372,verbal_rating:"GOOD"},
{name:"RIVERDALE AVE",numerical_rating:5.079,verbal_rating:"GOOD"},
{name:"FIELDSTON ROAD",numerical_rating:4.900,verbal_rating:"FAIR"},
{name:"HHP",numerical_rating:4.830,verbal_rating:"FAIR"},
{name:"VAN CRTLDT PARK",numerical_rating:4.759,verbal_rating:"FAIR"},
{name:"VAN CRTLDT EQUES",numerical_rating:4.600,verbal_rating:"FAIR"},
{name:"BRONX PELHAM PKWY",numerical_rating:4.486,verbal_rating:"FAIR"},
{name:"BOSTON ROAD",numerical_rating:4.042,verbal_rating:"FAIR"},
{name:"HIGHLAND BLVD E.B.",numerical_rating:4.724,verbal_rating:"FAIR"},
{name:"HIGHLAND BLVD W.B.",numerical_rating:4.767,verbal_rating:"FAIR"},
{name:"HIGHLAND BLVD W.B.",numerical_rating:4.974,verbal_rating:"FAIR"},
{name:"CYPRESS HILLS ST",numerical_rating:4.722,verbal_rating:"FAIR"},
{name:"JACKIE ROBINSON PKWY",numerical_rating:5.444,verbal_rating:"GOOD"},
{name:"MYRTLE AVE",numerical_rating:5.250,verbal_rating:"GOOD"},
{name:"JACKIE ROBINSON PKWY",numerical_rating:5.286,verbal_rating:"GOOD"},
{name:"UNION TPKE",numerical_rating:5.672,verbal_rating:"GOOD"},
{name:"MARKWOOD ROAD",numerical_rating:5.167,verbal_rating:"GOOD"},
{name:"QUEENS BLVD",numerical_rating:4.841,verbal_rating:"FAIR"},
{name:"HIGHLAND BLVD NB",numerical_rating:5.762,verbal_rating:"GOOD"},
{name:"MOSHOLU PARKWAY",numerical_rating:4.263,verbal_rating:"FAIR"},
{name:"MOSHOLU PARKWAY",numerical_rating:5.391,verbal_rating:"GOOD"},
{name:"MOSHOLU PARKWAY",numerical_rating:5.203,verbal_rating:"GOOD"},
{name:"JEROME AVE",numerical_rating:4.711,verbal_rating:"FAIR"},
{name:"MOSHOLU PARKWAY",numerical_rating:4.310,verbal_rating:"FAIR"},
{name:"MOSHOLU PARKWAY",numerical_rating:4.271,verbal_rating:"FAIR"},
{name:"MOSHOLU PARKWAY",numerical_rating:4.919,verbal_rating:"FAIR"},
{name:"SUMMIT ST PED BRDG",numerical_rating:4.557,verbal_rating:"FAIR"},
{name:"UNION ST",numerical_rating:4.236,verbal_rating:"FAIR"},
{name:"SACKETT ST",numerical_rating:4.500,verbal_rating:"FAIR"},
{name:"KANE ST",numerical_rating:4.153,verbal_rating:"FAIR"},
{name:"CONGRESS ST",numerical_rating:6.029,verbal_rating:"VGOOD"},
{name:"278I EB (B.Q.E.)",numerical_rating:4.500,verbal_rating:"FAIR"},
{name:"278I WB (B.Q.E.)",numerical_rating:5.047,verbal_rating:"GOOD"},
{name:"278I  (B.Q.E.) RAMP TO BKLN BRDG",numerical_rating:5.000,verbal_rating:"GOOD"},
{name:"278I WB (B.Q.E.)",numerical_rating:5.200,verbal_rating:"GOOD"},
{name:"278I EB (B.Q.E.)",numerical_rating:4.933,verbal_rating:"FAIR"},
{name:"278I  (B.Q.E.)",numerical_rating:5.467,verbal_rating:"GOOD"},
{name:"278I  (B.Q.E.)",numerical_rating:4.833,verbal_rating:"FAIR"},
{name:"278I  (B.Q.E.)",numerical_rating:4.852,verbal_rating:"FAIR"},
{name:"278I  (B.Q.E.)",numerical_rating:5.019,verbal_rating:"GOOD"},
{name:"278I  (B.Q.E.)",numerical_rating:4.967,verbal_rating:"FAIR"},
{name:"278I  (B.Q.E.)",numerical_rating:5.169,verbal_rating:"GOOD"},
{name:"65TH PLACE",numerical_rating:5.889,verbal_rating:"GOOD"},
{name:"QUEENS BLVD",numerical_rating:6.306,verbal_rating:"VGOOD"},
{name:"WOODSIDE AVE",numerical_rating:5.672,verbal_rating:"GOOD"},
{name:"69TH ST",numerical_rating:5.263,verbal_rating:"GOOD"},
{name:"70TH ST",numerical_rating:6.556,verbal_rating:"VGOOD"},
{name:"41ST AVE",numerical_rating:6.735,verbal_rating:"VGOOD"},
{name:"ROOSEVELT AVE",numerical_rating:5.431,verbal_rating:"GOOD"},
{name:"BROADWAY / 37TH AVE",numerical_rating:5.579,verbal_rating:"GOOD"},
{name:"STEINWAY ST",numerical_rating:6.349,verbal_rating:"VGOOD"},
{name:"STEINWAY ST",numerical_rating:6.349,verbal_rating:"VGOOD"},
{name:"37TH ST",numerical_rating:4.681,verbal_rating:"FAIR"},
{name:"35TH ST",numerical_rating:4.667,verbal_rating:"FAIR"},
{name:"32ND ST",numerical_rating:4.875,verbal_rating:"FAIR"},
{name:"31ST ST",numerical_rating:4.514,verbal_rating:"FAIR"},
{name:"278I  (B.Q.E.)",numerical_rating:6.051,verbal_rating:"VGOOD"},
{name:"278I  (B.Q.E.)",numerical_rating:5.983,verbal_rating:"GOOD"},
{name:"278I  (B.Q.E.)",numerical_rating:6.016,verbal_rating:"VGOOD"},
{name:"278I NB (BQE WEST LEG)",numerical_rating:6.407,verbal_rating:"VGOOD"},
{name:"278I NB (BQE EAST LEG)",numerical_rating:6.352,verbal_rating:"VGOOD"},
{name:"278I SB  (BQE WEST LEG)",numerical_rating:6.424,verbal_rating:"VGOOD"},
{name:"278I SB  (BQE EAST LEG)",numerical_rating:6.152,verbal_rating:"VGOOD"},
{name:"31ST AVE",numerical_rating:5.767,verbal_rating:"GOOD"},
{name:"278I SB (BQE WEST LEG)",numerical_rating:5.978,verbal_rating:"GOOD"},
{name:"278I SB (BQE EAST LEG)",numerical_rating:6.424,verbal_rating:"VGOOD"},
{name:"278I NB (BQE EAST LEG)",numerical_rating:6.356,verbal_rating:"VGOOD"},
{name:"278I (BQE WEST LEG)",numerical_rating:6.102,verbal_rating:"VGOOD"},
{name:"278I (BQE EAST LEG)",numerical_rating:6.206,verbal_rating:"VGOOD"},
{name:"BULOVA AVE",numerical_rating:5.278,verbal_rating:"GOOD"},
{name:"49TH ST",numerical_rating:5.278,verbal_rating:"GOOD"},
{name:"ASTORIA BLVD EB",numerical_rating:4.279,verbal_rating:"FAIR"},
{name:"47TH ST",numerical_rating:4.889,verbal_rating:"FAIR"},
{name:"278I NB (BQE WEST LEG)",numerical_rating:4.583,verbal_rating:"FAIR"},
{name:"44TH ST",numerical_rating:4.764,verbal_rating:"FAIR"},
{name:"278I WB (B.Q.E.)",numerical_rating:5.000,verbal_rating:"GOOD"},
{name:"278I EB (B.Q.E.)",numerical_rating:4.619,verbal_rating:"FAIR"},
{name:"QUEENS BLVD",numerical_rating:5.659,verbal_rating:"GOOD"},
{name:"COLUMBIA HEIGHTS",numerical_rating:4.450,verbal_rating:"FAIR"},
{name:"278I W.B.  (B.Q.E.)",numerical_rating:4.403,verbal_rating:"FAIR"},
{name:"278I E.B.  (B.Q.E.)",numerical_rating:5.263,verbal_rating:"GOOD"},
{name:"49TH ST",numerical_rating:4.444,verbal_rating:"FAIR"},
{name:"BSHP",numerical_rating:6.905,verbal_rating:"VGOOD"},
{name:"81ST ST PED BRDG",numerical_rating:4.761,verbal_rating:"FAIR"},
{name:"92ND ST PED BRDG",numerical_rating:3.770,verbal_rating:"FAIR"},
{name:"4TH AVE",numerical_rating:4.763,verbal_rating:"FAIR"},
{name:"BAY 8TH ST",numerical_rating:5.730,verbal_rating:"GOOD"},
{name:"17TH AVE PED BRDG",numerical_rating:3.702,verbal_rating:"FAIR"},
{name:"BSHP",numerical_rating:4.533,verbal_rating:"FAIR"},
{name:"BSHP",numerical_rating:4.600,verbal_rating:"FAIR"},
{name:"27TH AVE PED BRDG",numerical_rating:4.067,verbal_rating:"FAIR"},
{name:"CROPSEY AVE",numerical_rating:4.639,verbal_rating:"FAIR"},
{name:"BSHP",numerical_rating:6.448,verbal_rating:"VGOOD"},
{name:"GUIDER AV RAMP TO BSHP",numerical_rating:6.778,verbal_rating:"VGOOD"},
{name:"CONEY ISLAND AVE",numerical_rating:5.542,verbal_rating:"GOOD"},
{name:"E 12TH ST",numerical_rating:4.542,verbal_rating:"FAIR"},
{name:"BSHP",numerical_rating:4.738,verbal_rating:"FAIR"},
{name:"BSHP",numerical_rating:4.306,verbal_rating:"FAIR"},
{name:"BSHP",numerical_rating:4.278,verbal_rating:"FAIR"},
{name:"BSHP",numerical_rating:4.264,verbal_rating:"FAIR"},
{name:"KNAPP ST",numerical_rating:4.313,verbal_rating:"FAIR"},
{name:"BSHP",numerical_rating:3.239,verbal_rating:"FAIR"},
{name:"FLATBUSH AVE",numerical_rating:6.088,verbal_rating:"VGOOD"},
{name:"BSHP",numerical_rating:3.209,verbal_rating:"FAIR"},
{name:"BSHP WB",numerical_rating:6.758,verbal_rating:"VGOOD"},
{name:"BSHP EB",numerical_rating:7.000,verbal_rating:"VGOOD"},
{name:"BSHP",numerical_rating:7.000,verbal_rating:"VGOOD"},
{name:"BSHP",numerical_rating:6.577,verbal_rating:"VGOOD"},
{name:"PENNSYLVANIA AVE",numerical_rating:5.583,verbal_rating:"GOOD"},
{name:"CROSS BAY BLVD",numerical_rating:5.083,verbal_rating:"GOOD"},
{name:"S CONDUIT BLVD",numerical_rating:5.268,verbal_rating:"GOOD"},
{name:"COHANCY ST",numerical_rating:4.395,verbal_rating:"FAIR"},
{name:"130TH ST",numerical_rating:4.659,verbal_rating:"FAIR"},
{name:"GUY R. BREWER BLVD",numerical_rating:6.028,verbal_rating:"VGOOD"},
{name:"FARMERS BLVD",numerical_rating:4.477,verbal_rating:"FAIR"},
{name:"SPRINGFIELD BLVD",numerical_rating:4.591,verbal_rating:"FAIR"},
{name:"225TH ST",numerical_rating:4.614,verbal_rating:"FAIR"},
{name:"SUNRISE HWY W.B.",numerical_rating:4.262,verbal_rating:"FAIR"},
{name:"SUNRISE HWY W.B.",numerical_rating:4.565,verbal_rating:"FAIR"},
{name:"N CONDUIT AVE WB",numerical_rating:4.917,verbal_rating:"FAIR"},
{name:"N CONDUIT AVE WB",numerical_rating:4.932,verbal_rating:"FAIR"},
{name:"FRANCIS LEWIS BLVD",numerical_rating:5.033,verbal_rating:"GOOD"},
{name:"FRANCIS LEWIS BLVD",numerical_rating:4.700,verbal_rating:"FAIR"},
{name:"MERRICK BLVD",numerical_rating:4.467,verbal_rating:"FAIR"},
{name:"MERRICK BLVD",numerical_rating:4.200,verbal_rating:"FAIR"},
{name:"130TH AVE",numerical_rating:5.133,verbal_rating:"GOOD"},
{name:"130TH AVE",numerical_rating:4.700,verbal_rating:"FAIR"},
{name:"LINDEN BLVD",numerical_rating:4.432,verbal_rating:"FAIR"},
{name:"BCIP",numerical_rating:4.233,verbal_rating:"FAIR"},
{name:"BELMONT PARK SO. RAMP",numerical_rating:4.781,verbal_rating:"FAIR"},
{name:"HEMPSTEAD AVE",numerical_rating:4.000,verbal_rating:"FAIR"},
{name:"BELMONT PARK NO. RAMP",numerical_rating:4.563,verbal_rating:"FAIR"},
{name:"SUPERIOR ROAD",numerical_rating:4.682,verbal_rating:"FAIR"},
{name:"JAMAICA AVE",numerical_rating:4.773,verbal_rating:"FAIR"},
{name:"BRADDOCK AVE",numerical_rating:4.886,verbal_rating:"FAIR"},
{name:"HILLSIDE AVE",numerical_rating:4.211,verbal_rating:"FAIR"},
{name:"UNION TPKE",numerical_rating:4.409,verbal_rating:"FAIR"},
{name:"W ALLEY ROAD",numerical_rating:5.368,verbal_rating:"GOOD"},
{name:"NORTHERN BLVD",numerical_rating:5.764,verbal_rating:"GOOD"},
{name:"CROCHERON PK PED",numerical_rating:3.800,verbal_rating:"FAIR"},
{name:"28TH AVE PED BRDG",numerical_rating:4.615,verbal_rating:"FAIR"},
{name:"BCIP",numerical_rating:4.609,verbal_rating:"FAIR"},
{name:"UTOPIA PKWY",numerical_rating:5.341,verbal_rating:"GOOD"},
{name:"160TH ST",numerical_rating:5.694,verbal_rating:"GOOD"},
{name:"FRANCIS LEWIS BLVD",numerical_rating:4.682,verbal_rating:"FAIR"},
{name:"CLINTONVILLE ST",numerical_rating:4.705,verbal_rating:"FAIR"},
{name:"150TH ST",numerical_rating:4.591,verbal_rating:"FAIR"},
{name:"149TH ST",numerical_rating:4.795,verbal_rating:"FAIR"},
{name:"14TH AVE",numerical_rating:4.523,verbal_rating:"FAIR"},
{name:"147TH ST",numerical_rating:4.705,verbal_rating:"FAIR"},
{name:"BATTERY PLACE",numerical_rating:5.182,verbal_rating:"GOOD"},
{name:"FDR DR N.B. OFF RMP",numerical_rating:4.493,verbal_rating:"FAIR"},
{name:"STH ST RMP TO FDR S.B.",numerical_rating:3.881,verbal_rating:"FAIR"},
{name:"FDR DR S.B. OFF RMP",numerical_rating:5.209,verbal_rating:"GOOD"},
{name:"RAMP TO N.B. FDR DRIVE",numerical_rating:4.967,verbal_rating:"FAIR"},
{name:"CORLEARS PARK ROAD",numerical_rating:3.813,verbal_rating:"FAIR"},
{name:"DELANCEY ST PED BRDG",numerical_rating:4.443,verbal_rating:"FAIR"},
{name:"HOUSTON ST",numerical_rating:3.750,verbal_rating:"FAIR"},
{name:"FDR NB RAMP TO HOUSTON ST",numerical_rating:4.706,verbal_rating:"FAIR"},
{name:"HOUSTON ST RAMP TO FDR NB",numerical_rating:4.792,verbal_rating:"FAIR"},
{name:"E 6TH ST PED BRDG",numerical_rating:4.233,verbal_rating:"FAIR"},
{name:"E 25TH ST PED BRDG",numerical_rating:4.600,verbal_rating:"FAIR"},
{name:"E 51ST ST PED BRDG",numerical_rating:4.417,verbal_rating:"FAIR"},
{name:"E 63TH ST PED BRDG",numerical_rating:4.912,verbal_rating:"FAIR"},
{name:"E 71ST ST PED BRDG",numerical_rating:4.761,verbal_rating:"FAIR"},
{name:"E 78TH ST PED BRDG",numerical_rating:6.700,verbal_rating:"VGOOD"},
{name:"PROMENADE OVER FDR",numerical_rating:3.143,verbal_rating:"FAIR"},
{name:"E 103RD ST PED BRDG",numerical_rating:4.512,verbal_rating:"FAIR"},
{name:"E 111TH ST PED BRDG",numerical_rating:4.319,verbal_rating:"FAIR"},
{name:"E 120TH ST PED BRDG",numerical_rating:4.114,verbal_rating:"FAIR"},
{name:"E 10TH ST PED BRDG",numerical_rating:4.596,verbal_rating:"FAIR"},
{name:"FDR DRIVE SB",numerical_rating:6.563,verbal_rating:"VGOOD"},
{name:"E 60TH ST",numerical_rating:4.972,verbal_rating:"FAIR"},
{name:"HARLEM RIVER DRIVE",numerical_rating:3.493,verbal_rating:"FAIR"},
{name:"E 14 ST PED BRDG",numerical_rating:4.164,verbal_rating:"FAIR"},
{name:"BROOKLYN BRIDGE",numerical_rating:3.139,verbal_rating:"FAIR"},
{name:"PARK ROW TO BKLN",numerical_rating:5.086,verbal_rating:"GOOD"},
{name:"TO BKLN FRM FDR",numerical_rating:4.926,verbal_rating:"FAIR"},
{name:"PEARL ST TO BKLN",numerical_rating:3.814,verbal_rating:"FAIR"},
{name:"TO FDR DR N.B.",numerical_rating:4.528,verbal_rating:"FAIR"},
{name:"TO PEARL ST",numerical_rating:4.944,verbal_rating:"FAIR"},
{name:"PEARL ST TO FDR DR",numerical_rating:5.028,verbal_rating:"GOOD"},
{name:"TO PARK ROW",numerical_rating:4.549,verbal_rating:"FAIR"},
{name:"MANHATTAN BRIDGE(LL)",numerical_rating:4.375,verbal_rating:"FAIR"},
{name:"MANHATTAN BRIDGE(UL)",numerical_rating:3.757,verbal_rating:"FAIR"},
{name:"WILLIAMSBURG BRIDGE",numerical_rating:4.542,verbal_rating:"FAIR"},
{name:"QUEENSBORO BRIDGE (LL)",numerical_rating:4.167,verbal_rating:"FAIR"},
{name:"QUEENSBORO BRIDGE (UL)",numerical_rating:4.340,verbal_rating:"FAIR"},
{name:"TO E 60TH ST FROM QNS",numerical_rating:5.338,verbal_rating:"GOOD"},
{name:"TO QNS FROM E 59TH ST",numerical_rating:5.542,verbal_rating:"GOOD"},
{name:"TO E 62ND ST FROM QNS",numerical_rating:4.985,verbal_rating:"FAIR"},
{name:"TO QNS FROM E 58TH ST",numerical_rating:4.396,verbal_rating:"FAIR"},
{name:"TO NY FR THOMSON AVE",numerical_rating:4.679,verbal_rating:"FAIR"},
{name:"TO NY FROM 21ST ST",numerical_rating:4.712,verbal_rating:"FAIR"},
{name:"TO NY FROM 11TH ST",numerical_rating:5.268,verbal_rating:"GOOD"},
{name:"TO 21ST ST FROM NY",numerical_rating:4.366,verbal_rating:"FAIR"},
{name:"TO THOMSON AVE FROM NY",numerical_rating:5.148,verbal_rating:"GOOD"},
{name:"25X TO/FROM 2ND AVE",numerical_rating:4.829,verbal_rating:"FAIR"},
{name:"WILLIS AVE BRIDGE",numerical_rating:6.778,verbal_rating:"VGOOD"},
{name:"RAMP FROM FDR DRIVE",numerical_rating:6.887,verbal_rating:"VGOOD"},
{name:"TO BRUCKNER BLVD",numerical_rating:6.775,verbal_rating:"VGOOD"},
{name:"THIRD AVE BRIDGE",numerical_rating:5.789,verbal_rating:"GOOD"},
{name:"FROM BRUCKNER BLVD",numerical_rating:6.310,verbal_rating:"VGOOD"},
{name:"MADISON AVE BRIDGE",numerical_rating:4.861,verbal_rating:"FAIR"},
{name:"RAMP TO MADISON AVENUE",numerical_rating:5.028,verbal_rating:"GOOD"},
{name:"145TH ST BRIDGE",numerical_rating:6.278,verbal_rating:"VGOOD"},
{name:"W 207TH/W FORDHAM RD",numerical_rating:5.000,verbal_rating:"GOOD"},
{name:"BROADWAY BRIDGE",numerical_rating:3.806,verbal_rating:"FAIR"},
{name:"NYCTA IRT",numerical_rating:4.720,verbal_rating:"FAIR"},
{name:"WESTCHESTER AVE",numerical_rating:4.667,verbal_rating:"FAIR"},
{name:"SHORE ROAD",numerical_rating:4.299,verbal_rating:"FAIR"},
{name:"CITY ISLAND ROAD",numerical_rating:3.444,verbal_rating:"FAIR"},
{name:"HAMILTON AVE BRIDGE",numerical_rating:5.472,verbal_rating:"GOOD"},
{name:"HAMILTON AVE BRIDGE",numerical_rating:5.361,verbal_rating:"GOOD"},
{name:"NINTH ST BRIDGE",numerical_rating:6.161,verbal_rating:"VGOOD"},
{name:"THIRD ST",numerical_rating:4.722,verbal_rating:"FAIR"},
{name:"CARROLL ST",numerical_rating:4.931,verbal_rating:"FAIR"},
{name:"UNION ST",numerical_rating:4.111,verbal_rating:"FAIR"},
{name:"METROPOLITAN AVE",numerical_rating:5.778,verbal_rating:"GOOD"},
{name:"CROPSEY AVE SB",numerical_rating:5.000,verbal_rating:"GOOD"},
{name:"CROPSEY AVE NB",numerical_rating:4.718,verbal_rating:"FAIR"},
{name:"THIRD AVE",numerical_rating:6.550,verbal_rating:"VGOOD"},
{name:"OCEAN AVE PED BRDG",numerical_rating:5.000,verbal_rating:"GOOD"},
{name:"RICHMOND AVE",numerical_rating:5.194,verbal_rating:"GOOD"},
{name:"GREENPOINT AVE BRIDGE",numerical_rating:5.083,verbal_rating:"GOOD"},
{name:"GRAND ST BRIDGE",numerical_rating:4.014,verbal_rating:"FAIR"},
{name:"BORDEN AVE",numerical_rating:4.806,verbal_rating:"FAIR"},
{name:"NORTHERN BLVD",numerical_rating:4.681,verbal_rating:"FAIR"},
{name:"HUNTERS PT AVE",numerical_rating:5.056,verbal_rating:"GOOD"},
{name:"ROOSEVELT AVE",numerical_rating:3.521,verbal_rating:"FAIR"},
{name:"STILLWELL AVE",numerical_rating:6.125,verbal_rating:"VGOOD"},
{name:"WARDS ISLAND PED BRDG",numerical_rating:5.067,verbal_rating:"GOOD"},
{name:"PULASKI BRIDGE",numerical_rating:4.437,verbal_rating:"FAIR"},
{name:"ROOSEVELT ISLAND BRDG",numerical_rating:5.569,verbal_rating:"GOOD"},
{name:"163RD AVE PED BRDG",numerical_rating:4.037,verbal_rating:"FAIR"},
{name:"RIKERS ISLAND BRIDGE",numerical_rating:4.324,verbal_rating:"FAIR"},
{name:"WESTCHESTER AVE",numerical_rating:4.660,verbal_rating:"FAIR"},
{name:"E 156TH STREET",numerical_rating:4.612,verbal_rating:"FAIR"},
{name:"E 161ST STREET",numerical_rating:5.800,verbal_rating:"GOOD"},
{name:"E 163RD STREET",numerical_rating:4.611,verbal_rating:"FAIR"},
{name:"THIRD AVE",numerical_rating:4.563,verbal_rating:"FAIR"},
{name:"E 149TH ST/JACKSON AVE",numerical_rating:4.817,verbal_rating:"FAIR"},
{name:"ST. MARYS & CONCORD",numerical_rating:5.370,verbal_rating:"GOOD"},
{name:"WALES AVE",numerical_rating:6.467,verbal_rating:"VGOOD"},
{name:"SOUTHERN BLVD",numerical_rating:4.093,verbal_rating:"FAIR"},
{name:"BRUCKNER BLVD",numerical_rating:6.067,verbal_rating:"VGOOD"},
{name:"MELROSE AVE",numerical_rating:5.500,verbal_rating:"GOOD"},
{name:"E 149TH ST",numerical_rating:4.592,verbal_rating:"FAIR"},
{name:"LEGGETT AVE",numerical_rating:4.620,verbal_rating:"FAIR"},
{name:"LONGWOOD AVE",numerical_rating:5.236,verbal_rating:"GOOD"},
{name:"LAFAYETTE AVE",numerical_rating:5.365,verbal_rating:"GOOD"},
{name:"TIFFANY ST",numerical_rating:5.078,verbal_rating:"GOOD"},
{name:"BARRETTO ST",numerical_rating:5.813,verbal_rating:"GOOD"},
{name:"HUNTS POINT AVE",numerical_rating:4.813,verbal_rating:"FAIR"},
{name:"FAILE ST",numerical_rating:5.578,verbal_rating:"GOOD"},
{name:"BRYANT AVE",numerical_rating:3.186,verbal_rating:"FAIR"},
{name:"WESTCHESTER AVE",numerical_rating:5.778,verbal_rating:"GOOD"},
{name:"204TH ST PED BRDG",numerical_rating:3.845,verbal_rating:"FAIR"},
{name:"E 177TH ST",numerical_rating:5.278,verbal_rating:"GOOD"},
{name:"E TREMONT AVE",numerical_rating:5.153,verbal_rating:"GOOD"},
{name:"WHITE PLAINS ROAD",numerical_rating:4.781,verbal_rating:"FAIR"},
{name:"UNIONPORT ROAD",numerical_rating:4.688,verbal_rating:"FAIR"},
{name:"WILLIAMSBRIDGE RD",numerical_rating:4.985,verbal_rating:"FAIR"},
{name:"PELHAM BAY PK EQUES",numerical_rating:3.339,verbal_rating:"FAIR"},
{name:"SHORE RD CIRCLE",numerical_rating:7.000,verbal_rating:"VGOOD"},
{name:"GRAND CONCOURSE",numerical_rating:3.688,verbal_rating:"FAIR"},
{name:"WALTON AVE",numerical_rating:4.406,verbal_rating:"FAIR"},
{name:"GERARD AVE",numerical_rating:5.422,verbal_rating:"GOOD"},
{name:"RIVER AVE",numerical_rating:6.156,verbal_rating:"VGOOD"},
{name:"W TREMONT AVE",numerical_rating:3.776,verbal_rating:"FAIR"},
{name:"W FORDHAM RD",numerical_rating:5.694,verbal_rating:"GOOD"},
{name:"W 225TH ST",numerical_rating:5.269,verbal_rating:"GOOD"},
{name:"W 230TH ST",numerical_rating:5.125,verbal_rating:"GOOD"},
{name:"W 231ST ST",numerical_rating:4.745,verbal_rating:"FAIR"},
{name:"W 233RD ST",numerical_rating:5.275,verbal_rating:"GOOD"},
{name:"W 234TH ST",numerical_rating:5.176,verbal_rating:"GOOD"},
{name:"E 144TH ST",numerical_rating:5.847,verbal_rating:"GOOD"},
{name:"E 149TH ST",numerical_rating:4.625,verbal_rating:"FAIR"},
{name:"CONCOURSE VILL AVE",numerical_rating:3.969,verbal_rating:"FAIR"},
{name:"E 158TH ST",numerical_rating:5.200,verbal_rating:"GOOD"},
{name:"E 161ST ST",numerical_rating:5.050,verbal_rating:"GOOD"},
{name:"E 162ND ST",numerical_rating:4.781,verbal_rating:"FAIR"},
{name:"E 165TH ST",numerical_rating:4.300,verbal_rating:"FAIR"},
{name:"E 167TH ST",numerical_rating:5.510,verbal_rating:"GOOD"},
{name:"E 168TH ST",numerical_rating:4.641,verbal_rating:"FAIR"},
{name:"E 169TH ST",numerical_rating:4.188,verbal_rating:"FAIR"},
{name:"E 170TH ST",numerical_rating:6.333,verbal_rating:"VGOOD"},
{name:"ST PAULS PL PED BRDG",numerical_rating:4.746,verbal_rating:"FAIR"},
{name:"CLAREMONT PKWY",numerical_rating:6.458,verbal_rating:"VGOOD"},
{name:"E 173RD ST",numerical_rating:4.875,verbal_rating:"FAIR"},
{name:"E 175TH ST",numerical_rating:3.875,verbal_rating:"FAIR"},
{name:"E TREMONT AVE",numerical_rating:6.350,verbal_rating:"VGOOD"},
{name:"E 178TH ST PED BRDG",numerical_rating:4.921,verbal_rating:"FAIR"},
{name:"E 179TH ST PED BRDG",numerical_rating:5.311,verbal_rating:"GOOD"},
{name:"E 180TH ST",numerical_rating:3.844,verbal_rating:"FAIR"},
{name:"E 183TH ST",numerical_rating:3.953,verbal_rating:"FAIR"},
{name:"E 188TH ST",numerical_rating:4.094,verbal_rating:"FAIR"},
{name:"E 187TH ST",numerical_rating:4.344,verbal_rating:"FAIR"},
{name:"FORDHAM RD - E 189TH ST",numerical_rating:6.300,verbal_rating:"VGOOD"},
{name:"BEDFORD PARK BLVD",numerical_rating:4.656,verbal_rating:"FAIR"},
{name:"GUN HILL RD",numerical_rating:6.531,verbal_rating:"VGOOD"},
{name:"E 233RD ST",numerical_rating:4.902,verbal_rating:"FAIR"},
{name:"E 241ST ST",numerical_rating:4.639,verbal_rating:"FAIR"},
{name:"EASTCHESTER ROAD",numerical_rating:4.472,verbal_rating:"FAIR"},
{name:"GUN HILL ROAD",numerical_rating:5.516,verbal_rating:"GOOD"},
{name:"BEDFORD PARK BLVD",numerical_rating:5.347,verbal_rating:"GOOD"},
{name:"W 205TH ST",numerical_rating:5.514,verbal_rating:"GOOD"},
{name:"HUTCHINSON RVR PKWY",numerical_rating:5.542,verbal_rating:"GOOD"},
{name:"EAST FORDHAM RD",numerical_rating:5.467,verbal_rating:"GOOD"},
{name:"SOUTHERN BLVD",numerical_rating:4.605,verbal_rating:"FAIR"},
{name:"CROTONA AVE",numerical_rating:5.447,verbal_rating:"GOOD"},
{name:"BRONX BLVD S.B.",numerical_rating:4.367,verbal_rating:"FAIR"},
{name:"BRONX BLVD N.B.",numerical_rating:4.867,verbal_rating:"FAIR"},
{name:"BRONX BLVD S.B.",numerical_rating:4.300,verbal_rating:"FAIR"},
{name:"BRONX BLVD N.B.",numerical_rating:4.467,verbal_rating:"FAIR"},
{name:"PARK ROAD (204TH ST)",numerical_rating:4.655,verbal_rating:"FAIR"},
{name:"BOTANICAL GARDEN ROAD",numerical_rating:4.833,verbal_rating:"FAIR"},
{name:"BOSTON ROAD",numerical_rating:4.227,verbal_rating:"FAIR"},
{name:"FTBG N OF RTE 1 (HESTER BRDG)",numerical_rating:3.655,verbal_rating:"FAIR"},
{name:"E TREMONT AVE",numerical_rating:4.361,verbal_rating:"FAIR"},
{name:"MAGNOLIA WAY",numerical_rating:4.763,verbal_rating:"FAIR"},
{name:"SNUFF MILL ROAD",numerical_rating:4.395,verbal_rating:"FAIR"},
{name:"GRAND CONCOURSE",numerical_rating:6.333,verbal_rating:"VGOOD"},
{name:"EAGLE AVE",numerical_rating:5.117,verbal_rating:"GOOD"},
{name:"GRAND CONCOURSE",numerical_rating:4.754,verbal_rating:"FAIR"},
{name:"GRAND CONCOURSE",numerical_rating:4.733,verbal_rating:"FAIR"},
{name:"GRAND CONCOURSE",numerical_rating:4.754,verbal_rating:"FAIR"},
{name:"GRAND CONCOURSE",numerical_rating:4.067,verbal_rating:"FAIR"},
{name:"GRAND CONCOURSE",numerical_rating:4.833,verbal_rating:"FAIR"},
{name:"GRAND CONCOURSE",numerical_rating:5.583,verbal_rating:"GOOD"},
{name:"GRAND CONCOURSE",numerical_rating:4.714,verbal_rating:"FAIR"},
{name:"EAST FORDHAM RD",numerical_rating:4.833,verbal_rating:"FAIR"},
{name:"GRAND CONCOURSE",numerical_rating:4.265,verbal_rating:"FAIR"},
{name:"GRAND CONCOURSE",numerical_rating:4.373,verbal_rating:"FAIR"},
{name:"GRAND CONCOURSE",numerical_rating:5.406,verbal_rating:"GOOD"},
{name:"E 180TH ST",numerical_rating:4.810,verbal_rating:"FAIR"},
{name:"GUN HILL ROAD",numerical_rating:4.947,verbal_rating:"FAIR"},
{name:"GUN HILL ROAD",numerical_rating:5.300,verbal_rating:"GOOD"},
{name:"E 233RD ST",numerical_rating:4.233,verbal_rating:"FAIR"},
{name:"E 233RD ST",numerical_rating:4.900,verbal_rating:"FAIR"},
{name:"LINCOLN ROAD",numerical_rating:6.685,verbal_rating:"VGOOD"},
{name:"PARKSIDE AVE - OCEAN AVE",numerical_rating:4.043,verbal_rating:"FAIR"},
{name:"CROOKE AVE",numerical_rating:4.316,verbal_rating:"FAIR"},
{name:"CATON AVE",numerical_rating:4.842,verbal_rating:"FAIR"},
{name:"E 18TH ST - CHURCH AVE",numerical_rating:4.545,verbal_rating:"FAIR"},
{name:"BEVERLY ROAD",numerical_rating:4.088,verbal_rating:"FAIR"},
{name:"CORTELYOU ROAD",numerical_rating:6.083,verbal_rating:"VGOOD"},
{name:"DORCHESTER ROAD",numerical_rating:5.863,verbal_rating:"GOOD"},
{name:"DITMAS AVE",numerical_rating:5.723,verbal_rating:"GOOD"},
{name:"NEWKIRK AVE",numerical_rating:4.574,verbal_rating:"FAIR"},
{name:"FOSTER AVE",numerical_rating:4.283,verbal_rating:"FAIR"},
{name:"STERLING PLACE",numerical_rating:6.375,verbal_rating:"VGOOD"},
{name:"ST JOHNS PLACE",numerical_rating:6.656,verbal_rating:"VGOOD"},
{name:"LINCOLN PLACE",numerical_rating:6.672,verbal_rating:"VGOOD"},
{name:"UNION ST",numerical_rating:4.913,verbal_rating:"FAIR"},
{name:"PRESIDENT ST",numerical_rating:5.078,verbal_rating:"GOOD"},
{name:"CARROLL ST PED BRDG",numerical_rating:5.324,verbal_rating:"GOOD"},
{name:"CROWN ST",numerical_rating:5.069,verbal_rating:"GOOD"},
{name:"MONTGOMERY ST",numerical_rating:5.843,verbal_rating:"GOOD"},
{name:"WASHINGTON AVE",numerical_rating:6.000,verbal_rating:"GOOD"},
{name:"FLATBUSH AVE",numerical_rating:4.961,verbal_rating:"FAIR"},
{name:"EASTERN PKWY",numerical_rating:4.833,verbal_rating:"FAIR"},
{name:"6TH AVE",numerical_rating:5.431,verbal_rating:"GOOD"},
{name:"CARLTON AVE",numerical_rating:6.694,verbal_rating:"VGOOD"},
{name:"2ND AVE",numerical_rating:6.208,verbal_rating:"VGOOD"},
{name:"3RD AVE",numerical_rating:4.972,verbal_rating:"FAIR"},
{name:"4TH AVE",numerical_rating:5.486,verbal_rating:"GOOD"},
{name:"15TH AVE",numerical_rating:4.872,verbal_rating:"FAIR"},
{name:"60TH ST",numerical_rating:6.000,verbal_rating:"GOOD"},
{name:"16TH AVE",numerical_rating:5.350,verbal_rating:"GOOD"},
{name:"17TH AVE",numerical_rating:4.745,verbal_rating:"FAIR"},
{name:"18TH AVE",numerical_rating:4.625,verbal_rating:"FAIR"},
{name:"52ND ST",numerical_rating:6.017,verbal_rating:"VGOOD"},
{name:"50TH ST",numerical_rating:4.731,verbal_rating:"FAIR"},
{name:"MCDONALD AVE",numerical_rating:5.141,verbal_rating:"GOOD"},
{name:"E 3RD ST",numerical_rating:6.517,verbal_rating:"VGOOD"},
{name:"OCEAN PKWY",numerical_rating:4.927,verbal_rating:"FAIR"},
{name:"CONEY ISLAND AVE",numerical_rating:5.043,verbal_rating:"GOOD"},
{name:"E 14TH ST",numerical_rating:4.809,verbal_rating:"FAIR"},
{name:"E 15TH ST PED BRDG",numerical_rating:5.592,verbal_rating:"GOOD"},
{name:"OCEAN AVE",numerical_rating:4.965,verbal_rating:"FAIR"},
{name:"BEDFORD AVE",numerical_rating:5.097,verbal_rating:"GOOD"},
{name:"NOSTRAND AVE",numerical_rating:4.898,verbal_rating:"FAIR"},
{name:"FLATBUSH AVE",numerical_rating:4.651,verbal_rating:"FAIR"},
{name:"BROOKLYN AVE",numerical_rating:5.727,verbal_rating:"GOOD"},
{name:"ALBANY AVE - AVE H",numerical_rating:5.956,verbal_rating:"GOOD"},
{name:"ATLANTIC AVE",numerical_rating:3.620,verbal_rating:"FAIR"},
{name:"86TH ST",numerical_rating:5.797,verbal_rating:"GOOD"},
{name:"5TH AVE",numerical_rating:3.882,verbal_rating:"FAIR"},
{name:"6TH AVE",numerical_rating:6.056,verbal_rating:"VGOOD"},
{name:"7TH AVE",numerical_rating:4.806,verbal_rating:"FAIR"},
{name:"8TH AVE",numerical_rating:6.097,verbal_rating:"VGOOD"},
{name:"FORT HAMILTON PKWY",numerical_rating:4.729,verbal_rating:"FAIR"},
{name:"11TH AVE",numerical_rating:5.985,verbal_rating:"GOOD"},
{name:"13TH AVE",numerical_rating:4.972,verbal_rating:"FAIR"},
{name:"14TH AVE",numerical_rating:6.167,verbal_rating:"VGOOD"},
{name:"NEW UTRECHT AVE",numerical_rating:5.883,verbal_rating:"GOOD"},
{name:"15TH AVE",numerical_rating:6.114,verbal_rating:"VGOOD"},
{name:"16TH AVE",numerical_rating:5.481,verbal_rating:"GOOD"},
{name:"17TH AVE",numerical_rating:6.173,verbal_rating:"VGOOD"},
{name:"18TH AVE",numerical_rating:6.421,verbal_rating:"VGOOD"},
{name:"19TH AVE",numerical_rating:4.237,verbal_rating:"FAIR"},
{name:"20TH AVE",numerical_rating:6.421,verbal_rating:"VGOOD"},
{name:"65TH ST",numerical_rating:5.132,verbal_rating:"GOOD"},
{name:"BAY PKWY",numerical_rating:4.658,verbal_rating:"FAIR"},
{name:"AVENUE O",numerical_rating:5.706,verbal_rating:"GOOD"},
{name:"AVENUE P",numerical_rating:6.140,verbal_rating:"VGOOD"},
{name:"KINGS HIGHWAY",numerical_rating:6.628,verbal_rating:"VGOOD"},
{name:"HIGHLAWN AVE",numerical_rating:6.280,verbal_rating:"VGOOD"},
{name:"AVENUE S",numerical_rating:5.967,verbal_rating:"GOOD"},
{name:"AVENUE T",numerical_rating:6.000,verbal_rating:"GOOD"},
{name:"AVENUE U",numerical_rating:5.294,verbal_rating:"GOOD"},
{name:"21ST AVE",numerical_rating:4.026,verbal_rating:"FAIR"},
{name:"4TH AVE",numerical_rating:6.250,verbal_rating:"VGOOD"},
{name:"9TH AVE",numerical_rating:5.736,verbal_rating:"GOOD"},
{name:"LIBERTY AVE",numerical_rating:6.103,verbal_rating:"VGOOD"},
{name:"GLENMORE AVE",numerical_rating:6.456,verbal_rating:"VGOOD"},
{name:"PITKIN AVE",numerical_rating:6.279,verbal_rating:"VGOOD"},
{name:"SUTTER AVE",numerical_rating:6.292,verbal_rating:"VGOOD"},
{name:"BLAKE AVE",numerical_rating:4.927,verbal_rating:"FAIR"},
{name:"LIVONIA AVE PED BRDG",numerical_rating:4.833,verbal_rating:"FAIR"},
{name:"7TH AVE",numerical_rating:6.042,verbal_rating:"VGOOD"},
{name:"9TH AVE",numerical_rating:4.667,verbal_rating:"FAIR"},
{name:"EAST DR (ENDALE ARCH)",numerical_rating:4.300,verbal_rating:"FAIR"},
{name:"WEST DR (MEADOWPORT ARCH)",numerical_rating:5.321,verbal_rating:"GOOD"},
{name:"EAST DRIVE",numerical_rating:4.878,verbal_rating:"FAIR"},
{name:"EAST DR (EAST WOOD ARCH)",numerical_rating:4.667,verbal_rating:"FAIR"},
{name:"CENTER DR (NETHERMEAD ARCHES)",numerical_rating:5.000,verbal_rating:"GOOD"},
{name:"HILL DR (CLEFT RIDGE SPAN)",numerical_rating:4.433,verbal_rating:"FAIR"},
{name:"WEST FT BRDG (MUSIC GROVE  BRDG)",numerical_rating:5.000,verbal_rating:"GOOD"},
{name:"HILL DR (TERRACE BRDG)",numerical_rating:3.291,verbal_rating:"FAIR"},
{name:"PED NR BOATHSE (LULLWATER BRDG)",numerical_rating:4.885,verbal_rating:"FAIR"},
{name:"RIDGE BLVD",numerical_rating:6.333,verbal_rating:"VGOOD"},
{name:"3RD AVE",numerical_rating:6.273,verbal_rating:"VGOOD"},
{name:"ATLNTC AV SVC RD E.B.",numerical_rating:5.474,verbal_rating:"GOOD"},
{name:"ATLNTC AV SVC RD W.B.",numerical_rating:5.105,verbal_rating:"GOOD"},
{name:"FLEET WALK PED BRDG",numerical_rating:3.919,verbal_rating:"FAIR"},
{name:"CONDUIT BLVD NB",numerical_rating:4.833,verbal_rating:"FAIR"},
{name:"SEELEY ST",numerical_rating:4.033,verbal_rating:"FAIR"},
{name:"5TH AVE",numerical_rating:5.333,verbal_rating:"GOOD"},
{name:"11TH AVE VIADUCT",numerical_rating:4.056,verbal_rating:"FAIR"},
{name:"W 33RD ST",numerical_rating:4.500,verbal_rating:"FAIR"},
{name:"W 33RD ST",numerical_rating:4.500,verbal_rating:"FAIR"},
{name:"W 34TH ST",numerical_rating:4.375,verbal_rating:"FAIR"},
{name:"W 35TH ST",numerical_rating:4.181,verbal_rating:"FAIR"},
{name:"W 36TH ST",numerical_rating:4.433,verbal_rating:"FAIR"},
{name:"MARGARET CORBIN DR",numerical_rating:4.933,verbal_rating:"FAIR"},
{name:"MARGARET CORBIN DR",numerical_rating:4.433,verbal_rating:"FAIR"},
{name:"W 37TH ST",numerical_rating:6.079,verbal_rating:"VGOOD"},
{name:"W 38TH ST",numerical_rating:4.135,verbal_rating:"FAIR"},
{name:"W 39TH ST",numerical_rating:4.173,verbal_rating:"FAIR"},
{name:"W 43RD ST",numerical_rating:4.662,verbal_rating:"FAIR"},
{name:"W 44TH ST",numerical_rating:4.559,verbal_rating:"FAIR"},
{name:"W 45TH ST",numerical_rating:5.338,verbal_rating:"GOOD"},
{name:"W 46TH ST",numerical_rating:4.500,verbal_rating:"FAIR"},
{name:"W 47TH ST",numerical_rating:4.721,verbal_rating:"FAIR"},
{name:"W 48TH ST",numerical_rating:4.618,verbal_rating:"FAIR"},
{name:"W 49TH ST",numerical_rating:4.426,verbal_rating:"FAIR"},
{name:"W 51ST ST",numerical_rating:4.853,verbal_rating:"FAIR"},
{name:"W 52ND ST",numerical_rating:5.191,verbal_rating:"GOOD"},
{name:"W 53RD ST",numerical_rating:5.221,verbal_rating:"GOOD"},
{name:"W 58TH ST",numerical_rating:4.706,verbal_rating:"FAIR"},
{name:"11TH AVE",numerical_rating:4.426,verbal_rating:"FAIR"},
{name:"W 42ND ST",numerical_rating:4.587,verbal_rating:"FAIR"},
{name:"W 57TH ST",numerical_rating:4.853,verbal_rating:"FAIR"},
{name:"W 148TH ST PED BRDG",numerical_rating:4.200,verbal_rating:"FAIR"},
{name:"W 158TH ST",numerical_rating:5.917,verbal_rating:"GOOD"},
{name:"W 173RD ST PED BRDG",numerical_rating:4.600,verbal_rating:"FAIR"},
{name:"W 155TH ST PED BRDG",numerical_rating:3.862,verbal_rating:"FAIR"},
{name:"INWOOD HILL PK FTBR",numerical_rating:4.100,verbal_rating:"FAIR"},
{name:"E 97TH ST",numerical_rating:4.647,verbal_rating:"FAIR"},
{name:"W 41ST ST",numerical_rating:4.444,verbal_rating:"FAIR"},
{name:"W 50TH ST",numerical_rating:4.500,verbal_rating:"FAIR"},
{name:"W 54TH ST",numerical_rating:5.492,verbal_rating:"GOOD"},
{name:"W 55TH ST",numerical_rating:5.529,verbal_rating:"GOOD"},
{name:"W 56TH ST",numerical_rating:5.397,verbal_rating:"GOOD"},
{name:"TRANSVERSE RD #1 WB ",numerical_rating:5.000,verbal_rating:"GOOD"},
{name:"W 65TH ST ENTR EB",numerical_rating:5.100,verbal_rating:"GOOD"},
{name:"W 40TH ST",numerical_rating:4.103,verbal_rating:"FAIR"},
{name:"PARK AVE S.B.",numerical_rating:4.514,verbal_rating:"FAIR"},
{name:"PARK AVE N.B",numerical_rating:4.757,verbal_rating:"FAIR"},
{name:"TO GWB OPP W 171ST ST",numerical_rating:4.524,verbal_rating:"FAIR"},
{name:"WEST DR (GREYSHOT ARCH)",numerical_rating:5.400,verbal_rating:"GOOD"},
{name:"W 62 ST PED BRDG (PINEBANK ARCH)",numerical_rating:4.654,verbal_rating:"FAIR"},
{name:"E 62 ST PED BRDG (GAPSTOW BRDG)",numerical_rating:4.241,verbal_rating:"FAIR"},
{name:"EAST DR (INSCOPE ARCH)",numerical_rating:4.367,verbal_rating:"FAIR"},
{name:"CENTER DR (DRIPROCK ARCH)",numerical_rating:4.867,verbal_rating:"FAIR"},
{name:"EAST DR (GREEN GAP ARCH)",numerical_rating:4.433,verbal_rating:"FAIR"},
{name:"CENTER DR (PLAYMATES ARCH)",numerical_rating:4.500,verbal_rating:"FAIR"},
{name:"WEST DR (DALEHEAD ARCH)",numerical_rating:4.667,verbal_rating:"FAIR"},
{name:"PED BRDG OPP 65 ST",numerical_rating:4.583,verbal_rating:"FAIR"},
{name:"CENTER DRIVE",numerical_rating:4.467,verbal_rating:"FAIR"},
{name:"EAST DRIVE",numerical_rating:4.667,verbal_rating:"FAIR"},
{name:"WEST DRIVE",numerical_rating:4.700,verbal_rating:"FAIR"},
{name:"EAST DR (WILLOWDELL ARCH)",numerical_rating:3.500,verbal_rating:"FAIR"},
{name:"W 72 ST ENTR (RIFTSTONE ARCH)",numerical_rating:4.467,verbal_rating:"FAIR"},
{name:"72 ST CROSS DR (TERRACE BRDG)",numerical_rating:5.786,verbal_rating:"GOOD"},
{name:"73 ST PED BRDG (BOW BRIDGE)",numerical_rating:3.946,verbal_rating:"FAIR"},
{name:"EAST DR (TREFOIL ARCH)",numerical_rating:5.130,verbal_rating:"GOOD"},
{name:"EAST DRIVE",numerical_rating:4.600,verbal_rating:"FAIR"},
{name:"WEST DRIVE",numerical_rating:4.167,verbal_rating:"FAIR"},
{name:"EAST DRIVE",numerical_rating:4.300,verbal_rating:"FAIR"},
{name:"WEST DRIVE",numerical_rating:4.800,verbal_rating:"FAIR"},
{name:"EAST DRIVE",numerical_rating:4.100,verbal_rating:"FAIR"},
{name:"WEST DRIVE",numerical_rating:4.167,verbal_rating:"FAIR"},
{name:"W77 ST PED (OAK BRDG)",numerical_rating:5.368,verbal_rating:"GOOD"},
{name:"WEST DR (BALCONY BRDG)",numerical_rating:5.000,verbal_rating:"GOOD"},
{name:"W77 ST PED (LADIES POND BRDG)",numerical_rating:4.355,verbal_rating:"FAIR"},
{name:"EAST DR (GREYWACKE ARCH)",numerical_rating:3.733,verbal_rating:"FAIR"},
{name:"WEST DR (WINTERDALE ARCH)",numerical_rating:5.182,verbal_rating:"GOOD"},
{name:"W86 ST PED (SW RESERVOIR BRDG)",numerical_rating:4.852,verbal_rating:"FAIR"},
{name:"E86 ST PED (SE RESERVOIR BRDG)",numerical_rating:4.509,verbal_rating:"FAIR"},
{name:"PED PATH OPP E79 ST",numerical_rating:4.233,verbal_rating:"FAIR"},
{name:"TRNSVRS RD 1 EB (DENESMOUTH ARCH)",numerical_rating:4.636,verbal_rating:"FAIR"},
{name:"W110 ST ENTR (MOUNTCLIFF ARCH)",numerical_rating:4.317,verbal_rating:"FAIR"},
{name:"79 TH ST PED BRDG",numerical_rating:3.926,verbal_rating:"FAIR"},
{name:"E77 ST PED (GLADE ARCH)",numerical_rating:4.138,verbal_rating:"FAIR"},
{name:"W77 ST ENTR (EAGLEVALE ARCH)",numerical_rating:4.263,verbal_rating:"FAIR"},
{name:"EAST DR (HUDDLESTONE ARCH)",numerical_rating:4.500,verbal_rating:"FAIR"},
{name:"W 181 ST",numerical_rating:5.200,verbal_rating:"GOOD"},
{name:"A.C. POWELL BLVD N.B.",numerical_rating:4.347,verbal_rating:"FAIR"},
{name:"FORT TRYON PLACE",numerical_rating:4.200,verbal_rating:"FAIR"},
{name:"CORBIN PL OVERPASS",numerical_rating:5.000,verbal_rating:"GOOD"},
{name:"E 34TH ST",numerical_rating:4.117,verbal_rating:"FAIR"},
{name:"PARK AVE VIADUCT",numerical_rating:4.537,verbal_rating:"FAIR"},
{name:"TUDOR CITY PLACE",numerical_rating:5.133,verbal_rating:"GOOD"},
{name:"E42ND ST - E47TH ST",numerical_rating:4.922,verbal_rating:"FAIR"},
{name:"HIGH BRIDGE PDOVP",numerical_rating:3.759,verbal_rating:"FAIR"},
{name:"W 176TH ST PED BRDG",numerical_rating:4.533,verbal_rating:"FAIR"},
{name:"E 128TH ST PED BRDG",numerical_rating:3.939,verbal_rating:"FAIR"},
{name:"RIVERSIDE DRIVE",numerical_rating:4.444,verbal_rating:"FAIR"},
{name:"W 134 ST",numerical_rating:4.778,verbal_rating:"FAIR"},
{name:"ISHAM PK VEHICULR",numerical_rating:6.065,verbal_rating:"VGOOD"},
{name:"ISHAM PK PED BRDG",numerical_rating:4.138,verbal_rating:"FAIR"},
{name:"W 153 ST",numerical_rating:4.611,verbal_rating:"FAIR"},
{name:"RIVERSIDE DRIVE",numerical_rating:3.528,verbal_rating:"FAIR"},
{name:"RIVERSIDE DRIVE",numerical_rating:5.471,verbal_rating:"GOOD"},
{name:"RIVERSIDE DRIVE",numerical_rating:4.900,verbal_rating:"FAIR"},
{name:"E 129TH ST PED BRDG",numerical_rating:4.524,verbal_rating:"FAIR"},
{name:"94TH ST PED BRDG",numerical_rating:4.231,verbal_rating:"FAIR"},
{name:"UNION ST",numerical_rating:6.172,verbal_rating:"VGOOD"},
{name:"BOWNE ST",numerical_rating:5.451,verbal_rating:"GOOD"},
{name:"PARSONS BLVD",numerical_rating:4.824,verbal_rating:"FAIR"},
{name:"147TH ST",numerical_rating:5.392,verbal_rating:"GOOD"},
{name:"149TH ST",numerical_rating:4.776,verbal_rating:"FAIR"},
{name:"149TH PLACE",numerical_rating:5.000,verbal_rating:"GOOD"},
{name:"150TH ST",numerical_rating:6.088,verbal_rating:"VGOOD"},
{name:"MURRAY ST",numerical_rating:5.185,verbal_rating:"GOOD"},
{name:"WOODSIDE AVE",numerical_rating:4.413,verbal_rating:"FAIR"},
{name:"CORPORAL KENNEDY ST",numerical_rating:6.157,verbal_rating:"VGOOD"},
{name:"BELL BLVD",numerical_rating:5.610,verbal_rating:"GOOD"},
{name:"65TH ST",numerical_rating:6.375,verbal_rating:"VGOOD"},
{name:"65TH PLACE",numerical_rating:6.324,verbal_rating:"VGOOD"},
{name:"DOUGLASTON PKWY",numerical_rating:4.542,verbal_rating:"FAIR"},
{name:"GRAND AVE",numerical_rating:4.396,verbal_rating:"FAIR"},
{name:"55TH AVE PED BRDG",numerical_rating:4.120,verbal_rating:"FAIR"},
{name:"80TH ROAD",numerical_rating:4.698,verbal_rating:"FAIR"},
{name:"82ND AVE",numerical_rating:5.246,verbal_rating:"GOOD"},
{name:"LEFFERTS BLVD",numerical_rating:5.736,verbal_rating:"GOOD"},
{name:"JACKSON AVE",numerical_rating:5.550,verbal_rating:"GOOD"},
{name:"21ST ST",numerical_rating:5.153,verbal_rating:"GOOD"},
{name:"49TH AVE",numerical_rating:3.819,verbal_rating:"FAIR"},
{name:"THOMPSON AVE",numerical_rating:5.125,verbal_rating:"GOOD"},
{name:"QUEENS BLVD",numerical_rating:6.268,verbal_rating:"VGOOD"},
{name:"HONEYWELL ST",numerical_rating:5.792,verbal_rating:"GOOD"},
{name:"39TH ST (NORTH)",numerical_rating:6.208,verbal_rating:"VGOOD"},
{name:"37TH AVE",numerical_rating:5.894,verbal_rating:"GOOD"},
{name:"ROOSEVELT AVE",numerical_rating:6.208,verbal_rating:"VGOOD"},
{name:"41ST AVE",numerical_rating:4.788,verbal_rating:"FAIR"},
{name:"WOODSIDE AVE",numerical_rating:5.033,verbal_rating:"GOOD"},
{name:"43RD AVE",numerical_rating:5.000,verbal_rating:"GOOD"},
{name:"44TH AVE",numerical_rating:5.267,verbal_rating:"GOOD"},
{name:"45TH AVE",numerical_rating:5.224,verbal_rating:"GOOD"},
{name:"GRAND AVE",numerical_rating:6.183,verbal_rating:"VGOOD"},
{name:"57TH AVE",numerical_rating:5.976,verbal_rating:"GOOD"},
{name:"CALDWELL AVE",numerical_rating:5.889,verbal_rating:"GOOD"},
{name:"ELIOT AVE",numerical_rating:4.972,verbal_rating:"FAIR"},
{name:"JUNIPER BLVD SO",numerical_rating:4.833,verbal_rating:"FAIR"},
{name:"69TH STREET",numerical_rating:4.979,verbal_rating:"FAIR"},
{name:"METROPOLITAN AVE",numerical_rating:4.233,verbal_rating:"FAIR"},
{name:"ANDREWS AVE",numerical_rating:6.688,verbal_rating:"VGOOD"},
{name:"60TH ST",numerical_rating:5.208,verbal_rating:"GOOD"},
{name:"ELIOT AVE",numerical_rating:5.627,verbal_rating:"GOOD"},
{name:"80TH ST",numerical_rating:4.932,verbal_rating:"FAIR"},
{name:"FOREST PARK DRIVE",numerical_rating:5.158,verbal_rating:"GOOD"},
{name:"PARK LANE SOUTH",numerical_rating:6.983,verbal_rating:"VGOOD"},
{name:"MYRTLE AVE",numerical_rating:5.028,verbal_rating:"GOOD"},
{name:"PED BRG NEAR UNION TPK",numerical_rating:4.522,verbal_rating:"FAIR"},
{name:"39TH ST (SOUTH)",numerical_rating:5.667,verbal_rating:"GOOD"},
{name:"60TH RD PED BRDG",numerical_rating:5.000,verbal_rating:"GOOD"},
{name:"FOREST PARK DRIVE",numerical_rating:4.302,verbal_rating:"FAIR"},
{name:"221ST ST",numerical_rating:5.926,verbal_rating:"GOOD"},
{name:"WOODHAVEN BLVD",numerical_rating:4.208,verbal_rating:"FAIR"},
{name:"WHITELAW PED BRDG",numerical_rating:4.303,verbal_rating:"FAIR"},
{name:"CROSS BAY BLVD",numerical_rating:5.958,verbal_rating:"GOOD"},
{name:"RAMP TO LINDEN BLVD",numerical_rating:5.200,verbal_rating:"GOOD"},
{name:"MOTOR PKWY (PED)",numerical_rating:4.444,verbal_rating:"FAIR"},
{name:"MOTOR PKWY (PED)",numerical_rating:4.403,verbal_rating:"FAIR"},
{name:"MOTOR PKWY (PED)",numerical_rating:3.836,verbal_rating:"FAIR"},
{name:"MOTOR PKWY (PED)",numerical_rating:4.672,verbal_rating:"FAIR"},
{name:"FLSHG MDW PK PED",numerical_rating:4.639,verbal_rating:"FAIR"},
{name:"MOTOR PKWY (PED)",numerical_rating:4.672,verbal_rating:"FAIR"},
{name:"MOTOR PKWY (PED)",numerical_rating:3.833,verbal_rating:"FAIR"},
{name:"UNION TPKE",numerical_rating:4.733,verbal_rating:"FAIR"},
{name:"FLUSHING MEADOW PK PED",numerical_rating:1.000,verbal_rating:"CLOSED"},
{name:"FLUSHING MEADW PK RD",numerical_rating:4.481,verbal_rating:"FAIR"},
{name:"WOODHAVEN BLVD",numerical_rating:4.078,verbal_rating:"FAIR"},
{name:"ELIOT AVE",numerical_rating:4.804,verbal_rating:"FAIR"},
{name:"RUST ST",numerical_rating:4.672,verbal_rating:"FAIR"},
{name:"SERVICE RD TURNAROUND",numerical_rating:5.078,verbal_rating:"GOOD"},
{name:"BEACH CHANNEL DR WB",numerical_rating:4.400,verbal_rating:"FAIR"},
{name:"FLUSHING AV SERVICE RD",numerical_rating:5.250,verbal_rating:"GOOD"},
{name:"102ND ST",numerical_rating:6.015,verbal_rating:"VGOOD"},
{name:"MEADOW LAKE BRIDGE",numerical_rating:4.458,verbal_rating:"FAIR"},
{name:"HIGHLAND PK PED.",numerical_rating:3.667,verbal_rating:"FAIR"},
{name:"J.R. PKWY-UNION TPKE",numerical_rating:4.806,verbal_rating:"FAIR"},
{name:"71ST AVE",numerical_rating:4.373,verbal_rating:"FAIR"},
{name:"FOREST PARK DR",numerical_rating:4.984,verbal_rating:"FAIR"},
{name:"ROCKAWAY BLVD",numerical_rating:5.474,verbal_rating:"GOOD"},
{name:"BOATHOUSE BRIDGE",numerical_rating:4.296,verbal_rating:"FAIR"},
{name:"TOMPKINS AVE",numerical_rating:5.953,verbal_rating:"GOOD"},
{name:"JOHN ST PED BRDG",numerical_rating:5.423,verbal_rating:"GOOD"},
{name:"MORNINGSTAR ROAD",numerical_rating:4.627,verbal_rating:"FAIR"},
{name:"GRANITE AVE",numerical_rating:5.966,verbal_rating:"GOOD"},
{name:"LAKE AVE",numerical_rating:4.556,verbal_rating:"FAIR"},
{name:"SIMONSON AVE",numerical_rating:5.852,verbal_rating:"GOOD"},
{name:"VAN name AVE",numerical_rating:5.186,verbal_rating:"GOOD"},
{name:"VAN PELT AVE",numerical_rating:5.576,verbal_rating:"GOOD"},
{name:"DE HART AVE",numerical_rating:6.389,verbal_rating:"VGOOD"},
{name:"UNION AVE",numerical_rating:5.130,verbal_rating:"GOOD"},
{name:"HARBOR ROAD",numerical_rating:6.000,verbal_rating:"GOOD"},
{name:"SOUTH AVE",numerical_rating:6.527,verbal_rating:"VGOOD"},
{name:"MAIN ST PED BRDG",numerical_rating:4.263,verbal_rating:"FAIR"},
{name:"TRACY AVE PED BRDG",numerical_rating:3.894,verbal_rating:"FAIR"},
{name:"ARTHUR KILL ROAD",numerical_rating:4.796,verbal_rating:"FAIR"},
{name:"BETHEL AV PED BRDG",numerical_rating:3.754,verbal_rating:"FAIR"},
{name:"PAGE AVE",numerical_rating:5.806,verbal_rating:"GOOD"},
{name:"RICHMOND VALLEY ROAD",numerical_rating:5.164,verbal_rating:"GOOD"},
{name:"RICHMOND VALLEY STA PED BRDG",numerical_rating:4.393,verbal_rating:"FAIR"},
{name:"SEGUINE AVE",numerical_rating:6.016,verbal_rating:"VGOOD"},
{name:"HUGUENOT AVE",numerical_rating:4.788,verbal_rating:"FAIR"},
{name:"ALBEE AVE",numerical_rating:4.689,verbal_rating:"FAIR"},
{name:"ANNADALE ROAD",numerical_rating:6.233,verbal_rating:"VGOOD"},
{name:"NELSON AVE PED BRDG",numerical_rating:4.115,verbal_rating:"FAIR"},
{name:"GIFFORDS LANE",numerical_rating:5.625,verbal_rating:"GOOD"},
{name:"GREAVES AVE",numerical_rating:6.533,verbal_rating:"VGOOD"},
{name:"GUYON AVE",numerical_rating:4.672,verbal_rating:"FAIR"},
{name:"CEDARVIEW AVE PED BRDG",numerical_rating:3.615,verbal_rating:"FAIR"},
{name:"BEACH AVE",numerical_rating:5.364,verbal_rating:"GOOD"},
{name:"ROSS AVE",numerical_rating:5.182,verbal_rating:"GOOD"},
{name:"ROSE AVE",numerical_rating:5.258,verbal_rating:"GOOD"},
{name:"NEW DORP LANE",numerical_rating:4.955,verbal_rating:"FAIR"},
{name:"BANCROFT AVE",numerical_rating:5.393,verbal_rating:"GOOD"},
{name:"FREMONT AVE PED BRDG",numerical_rating:4.164,verbal_rating:"FAIR"},
{name:"LINCOLN AVE",numerical_rating:5.172,verbal_rating:"GOOD"},
{name:"MIDLAND AVE",numerical_rating:5.466,verbal_rating:"GOOD"},
{name:"WEST FINGERBOARD RD",numerical_rating:6.403,verbal_rating:"VGOOD"},
{name:"CLOVE ROAD",numerical_rating:5.778,verbal_rating:"GOOD"},
{name:"TOMPKINS AVE",numerical_rating:5.269,verbal_rating:"GOOD"},
{name:"HANNAH ST",numerical_rating:4.627,verbal_rating:"FAIR"},
{name:"MINTHORNE ST PED BRDG",numerical_rating:4.547,verbal_rating:"FAIR"},
{name:"BELFIELD AVE PED BRDG",numerical_rating:3.902,verbal_rating:"FAIR"},
{name:"WEST FOOTBRIDGE",numerical_rating:3.857,verbal_rating:"FAIR"},
{name:"EAST FOOTBRIDGE",numerical_rating:4.143,verbal_rating:"FAIR"},
{name:"BRIDGE OVER DAM",numerical_rating:3.351,verbal_rating:"FAIR"},
{name:"MARTLINGS AVE",numerical_rating:4.467,verbal_rating:"FAIR"},
{name:"S OF BROOKS LAKE",numerical_rating:4.651,verbal_rating:"FAIR"},
{name:"FOOTBRIDGE",numerical_rating:3.867,verbal_rating:"FAIR"},
{name:"FB S OF FOREST AV",numerical_rating:4.651,verbal_rating:"FAIR"},
{name:"FOREST AVE",numerical_rating:4.300,verbal_rating:"FAIR"},
{name:"HYLAN BLVD",numerical_rating:6.172,verbal_rating:"VGOOD"},
{name:"ARTHUR KILL ROAD",numerical_rating:4.102,verbal_rating:"FAIR"},
{name:"TOMPKINS AVE",numerical_rating:4.638,verbal_rating:"FAIR"},
{name:"SLATER BLVD",numerical_rating:5.510,verbal_rating:"GOOD"},
{name:"TRAVIS AVE",numerical_rating:5.483,verbal_rating:"GOOD"},
{name:"CHELSEA ROAD",numerical_rating:6.633,verbal_rating:"VGOOD"},
{name:"MILLER HWY - RTE 9A",numerical_rating:4.296,verbal_rating:"FAIR"},
{name:"DOUGLASTON PKWY",numerical_rating:4.592,verbal_rating:"FAIR"},
{name:"DOUGLASTON PKWY",numerical_rating:4.653,verbal_rating:"FAIR"},
{name:"HEMPSTEAD AVE",numerical_rating:4.190,verbal_rating:"FAIR"},
{name:"678I SB TO BCIP EB",numerical_rating:4.156,verbal_rating:"FAIR"},
{name:"HHP",numerical_rating:5.000,verbal_rating:"GOOD"},
{name:"HHP NB",numerical_rating:5.000,verbal_rating:"GOOD"},
{name:"HHP SB",numerical_rating:5.526,verbal_rating:"GOOD"},
{name:"278I",numerical_rating:4.435,verbal_rating:"FAIR"},
{name:"W 31ST ST",numerical_rating:3.619,verbal_rating:"FAIR"},
{name:"BCIP",numerical_rating:4.972,verbal_rating:"FAIR"},
{name:"RIVERSIDE DRIVE",numerical_rating:5.000,verbal_rating:"GOOD"},
{name:"ROOSEVELT AVE",numerical_rating:4.651,verbal_rating:"FAIR"},
{name:"FRANCIS LEWIS BLVD",numerical_rating:5.300,verbal_rating:"GOOD"},
{name:"HRD RAMP TO GWB",numerical_rating:3.042,verbal_rating:"FAIR"},
{name:"HHP",numerical_rating:3.548,verbal_rating:"FAIR"},
{name:"WEST STREET",numerical_rating:5.033,verbal_rating:"GOOD"},
{name:"79 ST PED PLAZA",numerical_rating:4.444,verbal_rating:"FAIR"},
{name:"79 ST TRAFFIC CIRC",numerical_rating:3.754,verbal_rating:"FAIR"},
{name:"79 ST RAMP TO HHP",numerical_rating:4.221,verbal_rating:"FAIR"},
{name:"79 ST RAMP TO GAR",numerical_rating:4.452,verbal_rating:"FAIR"},
{name:"GAR RAMP TO 79 ST",numerical_rating:4.435,verbal_rating:"FAIR"},
{name:"SB HHP RAMP TO 79 ST",numerical_rating:4.403,verbal_rating:"FAIR"},
{name:"BROOKLYN BR APPROACH",numerical_rating:4.344,verbal_rating:"FAIR"},
{name:"BROOKLYN PROMENADE",numerical_rating:3.828,verbal_rating:"FAIR"},
{name:"CHAMBERS ST PED BRDG",numerical_rating:5.391,verbal_rating:"GOOD"},
{name:"278I W.B.  (B.Q.E.)",numerical_rating:4.357,verbal_rating:"FAIR"},
{name:"278I E.B.  (B.Q.E.)",numerical_rating:3.754,verbal_rating:"FAIR"},
{name:"278I W.B.  (B.Q.E.)",numerical_rating:4.071,verbal_rating:"FAIR"},
{name:"278I E.B.  (B.Q.E.)",numerical_rating:4.297,verbal_rating:"FAIR"},
{name:"278I W.B.  (B.Q.E.)",numerical_rating:4.104,verbal_rating:"FAIR"},
{name:"278I E.B.  (B.Q.E.)",numerical_rating:4.119,verbal_rating:"FAIR"},
{name:"FDR NB E42ND TO E49TH ST",numerical_rating:3.836,verbal_rating:"FAIR"},
{name:"PS-5 PED BRDG",numerical_rating:4.347,verbal_rating:"FAIR"},
{name:"SPRINGFIELD BLVD",numerical_rating:4.889,verbal_rating:"FAIR"},
{name:"AMBOY ROAD",numerical_rating:6.333,verbal_rating:"VGOOD"},
{name:"MORRIS ST PED BRDG",numerical_rating:3.875,verbal_rating:"FAIR"},
{name:"MATTHEWSON ROAD",numerical_rating:4.175,verbal_rating:"FAIR"},
{name:"W 70TH ST",numerical_rating:5.542,verbal_rating:"GOOD"},
{name:"RIVERSIDE DRIVE SOUTH",numerical_rating:5.792,verbal_rating:"GOOD"},
{name:"W 68TH ST",numerical_rating:6.542,verbal_rating:"VGOOD"},
{name:"RIVERSIDE DRIVE",numerical_rating:4.640,verbal_rating:"FAIR"},
{name:"ERSKINE ST",numerical_rating:5.938,verbal_rating:"GOOD"},
{name:"PARKING EXIT RAMP",numerical_rating:6.097,verbal_rating:"VGOOD"},
{name:"BUS STATION NORTH",numerical_rating:5.600,verbal_rating:"GOOD"},
{name:"BUS STATION SOUTH",numerical_rating:5.280,verbal_rating:"GOOD"},
{name:"NORTH RAMP",numerical_rating:6.431,verbal_rating:"VGOOD"},
{name:"BUS STA ENTR RAMP",numerical_rating:5.431,verbal_rating:"GOOD"},
{name:"PARKING ENTR RAMP",numerical_rating:5.889,verbal_rating:"GOOD"},
{name:"BUS STATION EXIT RAMP",numerical_rating:5.167,verbal_rating:"GOOD"},
{name:"E 81 ST PED BRDG",numerical_rating:3.439,verbal_rating:"FAIR"},
{name:"E 156TH ST",numerical_rating:3.493,verbal_rating:"FAIR"},
{name:"SI FERRY PED BRDG",numerical_rating:5.600,verbal_rating:"GOOD"},
{name:"BOROUGH PLACE - RAMP A",numerical_rating:6.594,verbal_rating:"VGOOD"},
{name:"BROOKE AVE",numerical_rating:3.873,verbal_rating:"FAIR"},
{name:"ROCKAWAY BLVD",numerical_rating:5.763,verbal_rating:"GOOD"},
{name:"216TH ST PED BRDG",numerical_rating:3.111,verbal_rating:"FAIR"},
{name:"167TH ST PED BRDG",numerical_rating:4.000,verbal_rating:"FAIR"},
{name:"W191ST ST PED TNL",numerical_rating:4.364,verbal_rating:"FAIR"},
{name:"HHP ON/OFF RMP-79TH ST SO. SIDE",numerical_rating:4.500,verbal_rating:"FAIR"},
{name:"HHP ON/OFF RMP-79TH ST NO. SIDE",numerical_rating:4.667,verbal_rating:"FAIR"},
{name:"BCIP",numerical_rating:4.400,verbal_rating:"FAIR"}];